//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Film_Arşiv_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminGiri
    {
        public int ID { get; set; }
        public string Admin_Adı { get; set; }
        public string Sifre { get; set; }
    }
}
