//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Film_Arşiv_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.BiletSatış = new HashSet<BiletSatış>();
        }
    
        public int ID { get; set; }
        public string Film_Adı { get; set; }
        public string Yönetmen { get; set; }
        public Nullable<int> FilmTürüID { get; set; }
        public string FilmSüresi { get; set; }
        public Nullable<int> ÜlkeID { get; set; }
        public Nullable<System.DateTime> Vizyon_Tarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiletSatış> BiletSatış { get; set; }
        public virtual FilmTürü FilmTürü { get; set; }
        public virtual Ülke Ülke { get; set; }
    }
}
